---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pulsar-consumer
  namespace: default
spec:
  scaleTargetRef:
    name: pulsar-consumer
  pollingInterval: 5 # Optional. Default: 30 seconds
  cooldownPeriod: 30 # Optional. Default: 300 seconds
  maxReplicaCount: 30 # Optional. Default: 100
  triggers:
    - type: pulsar
      metadata:
        queueName: hello
        queueLength: "5"
        adminURL: https://pulsar-pulsar.default:8081
        tenant: public 
        namespace: default 
        topic:  persistent://public/default/keda
        subscription: keda
        tls: enable
      authenticationRef:
        name: pulsar-consumer-trigger
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: pulsar-consumer-trigger
  namespace: default
spec:
  secretTargetRef:
    - parameter: ca
      name: pulsar-pulsar
      key: ca
    - parameter: key
      name: pulsar-pulsar
      key: key
    - parameter: cert
      name: pulsar-pulsar
      key: cert
---
