apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-consumer
  namespace: default
  labels:
    app: pulsar-consumer
spec:
  selector:
    matchLabels:
      app: pulsar-consumer
  template:
    metadata:
      labels:
        app: pulsar-consumer
    spec:
      containers:
        - name: pulsar-consumer
          image: ghcr.io/pulsar-sigs/pulsar-client:v0.3.1
          imagePullPolicy: IfNotPresent
          readinessProbe:
            tcpSocket:
              port: 9494
          args: ["consumer","--broker","pulsar://pulsar-pulsar.default:6650","--topic","persistent://public/default/keda","--subscription-name","keda","--consume-time","200"]