apiVersion: batch/v1
kind: Job
metadata:
  name: pulsar-producer
spec:
  template:
    spec:
      containers:
      - name: rabbitmq-client
        image: ghcr.io/pulsar-sigs/pulsar-client:v0.1.0
        imagePullPolicy: IfNotPresent
        args: ["producer", "--broker","pulsar://pulsar.default","--topic","keda","--subscription-name","scaler"]
      restartPolicy: Never
  backoffLimit: 4

